In [2]:
from scipy import io as spio
import numpy as np

In [3]:
a = np.ones((3, 3))
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [4]:
spio.savemat('file.mat', {'a':a})

In [5]:
data = spio.loadmat('file.mat',struct_as_record=True)

In [6]:
data['a']

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
# 读取图片
import matplotlib.pyplot as plt
import os
os.environ['KMP_DUPLICATE_LIB_OK']='True'

In [17]:
img = plt.imread('image.png')
img_shape = img.shape  # 4 通道

In [18]:
img = img.reshape(-1, 4)
img[:, 3]=0.6  # 设置图透明度为0.6
img = img.reshape(img_shape)

In [19]:
plt.imsave('image-out.png', img)

In [22]:
# 载入txt
text = np.loadtxt('test.txt')
text

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.]])

In [23]:
text.dtype

dtype('float64')

In [25]:
np.save('out', text)

In [27]:
data = np.load('out.npy')
data

array([[1., 2., 3., 4.],
       [2., 3., 4., 5.]])