In [1]:
from scipy import linalg
import numpy as np

In [2]:
arr = np.array([[1, 2], [3, 4]])

In [3]:
arr

array([[1, 2],
       [3, 4]])

In [4]:
arr1 = np.arange(4).reshape((2, 2))
arr1

array([[0, 1],
       [2, 3]])

In [6]:
linalg.det(arr), linalg.inv(arr)

(-2.0,
 array([[-2. ,  1. ],
        [ 1.5, -0.5]]))

In [7]:
np.dot(arr, linalg.inv(arr))

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

In [17]:
labels = np.array([[1],[2],[0],[1]])
labels

array([[1],
       [2],
       [0],
       [1]])

In [18]:
np.eye(3)[labels.reshape(-1)]  # 通过本方式可以获得one-hot编码(生成单位矩阵并索引对应行)

array([[0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.]])