In [1]:
import torch
from torch import nn
from torch.nn import functional as F

In [7]:
# 不带参数的层
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
        
    def forward(self, X):
        return (X - X.mean()) / X.std()

In [8]:
layer = CenteredLayer()
layer(torch.FloatTensor([1, 2, 3, 4, 5]))

tensor([-1.2649, -0.6325,  0.0000,  0.6325,  1.2649])

In [9]:
# 在更复杂的网络中使用
net = nn.Sequential(nn.Linear(8, 128), CenteredLayer())
Y = net(torch.rand(4, 8))
Y.mean()

tensor(1.4901e-08, grad_fn=<MeanBackward0>)

In [17]:
# 带参数的层
class MyLinear(nn.Module):
    def __init__(self, in_uints, uints):
        super().__init__()
        self.weight = nn.Parameter(torch.rand(in_uints, uints))
        self.bias = nn.Parameter(torch.zeros(uints, ))
    def forward(self, X):
        linear = torch.matmul(X, self.weight.data) + self.bias.data
        return F.relu(linear)

linear = MyLinear(5, 3)
linear.weight

Parameter containing:
tensor([[0.0997, 0.3598, 0.9342],
        [0.4788, 0.8298, 0.0843],
        [0.9628, 0.7145, 0.6885],
        [0.4494, 0.0312, 0.7241],
        [0.6664, 0.2409, 0.1891]], requires_grad=True)

In [18]:
linear(torch.rand(2, 5))
net = nn.Sequential(MyLinear(64, 8), MyLinear(8, 1))
net(torch.rand(2, 64))

tensor([[56.7845],
        [53.3858]])